name: Trigger auto deployment for ws-broken-links-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/ws-broken-links-container-AutoDeployTrigger-004fbdca-ad84-410e-8f0d-0a96b5c134d2.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.WSBROKENLINKSCONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.WSBROKENLINKSCONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.WSBROKENLINKSCONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.WSBROKENLINKSCONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.WSBROKENLINKSCONTAINER_REGISTRY_PASSWORD }}
          containerAppName: ws-broken-links-container
          resourceGroup: ap_appservice
          imageToBuild: arundeep78/ws-broken-links-container:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


